---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tfout.wibrow.net
  resources:
  - terraformoutputs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tfout.wibrow.net
  resources:
  - terraformoutputs/finalizers
  verbs:
  - update
- apiGroups:
  - tfout.wibrow.net
  resources:
  - terraformoutputs/status
  verbs:
  - get
  - patch
  - update
