# permissions for end users to edit terraformoutputs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: tfout
    app.kubernetes.io/managed-by: kustomize
  name: terraformoutputs-editor-role
rules:
  - apiGroups:
      - tfout.wibrow.net
    resources:
      - terraformoutputs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - tfout.wibrow.net
    resources:
      - terraformoutputs/status
    verbs:
      - get
