# permissions for end users to view terraformoutputs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: tfout
    app.kubernetes.io/managed-by: kustomize
  name: terraformoutputs-viewer-role
rules:
  - apiGroups:
      - tfout.wibrow.net
    resources:
      - terraformoutputs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - tfout.wibrow.net
    resources:
      - terraformoutputs/status
    verbs:
      - get
