# permissions for end users to edit terraformoutputs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: tf-outputs-operator
    app.kubernetes.io/managed-by: kustomize
  name: terraformoutputs-editor-role
rules:
- apiGroups:
  - outputs.tfoutputs.io
  resources:
  - terraformoutputs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - outputs.tfoutputs.io
  resources:
  - terraformoutputs/status
  verbs:
  - get
