{{- if and .Values.rbac.create .Values.controller.leaderElection -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "tfout.fullname" . }}-leader-election-rolebinding
  labels:
    {{- include "tfout.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "tfout.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "tfout.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}