apiVersion: tfout.wibrow.net/v1alpha1
kind: TerraformOutputs
metadata:
  name: test-terraform-outputs
  namespace: default
spec:
  backends:
    - s3:
        bucket: "test-tf-operator"
        key: "test/terraform.tfstate"
        region: "eu-central-1"
    - s3:
        bucket: "test-tf-operator"
        key: "test/terraform-one.tfstate"
        region: "eu-central-1"
  syncInterval: "30s" # Fast sync for testing
  target:
    namespace: "default"
    configMapName: "terraform-outputs"
    secretName: "terraform-secrets"
