name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GO_VERSION: '1.24'

jobs:
  e2e:
    runs-on: ubuntu-latest
    concurrency:
      group: "e2e-${{ github.ref }}"
      cancel-in-progress: true
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}

    # - name: Cache Go modules
    #   uses: actions/cache@v4
    #   with:
    #     path: |
    #       ~/.cache/go-build
    #       ~/go/pkg/mod
    #     key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
    #     restore-keys: |
    #       ${{ runner.os }}-go-

    - name: Set up Kind
      uses: helm/kind-action@v1
      with:
        cluster_name: kind
        kubectl_version: v1.32.0

    - name: Wait for cluster to be ready
      run: |
        kubectl cluster-info
        kubectl wait --for=condition=Ready nodes --all --timeout=60s

    - name: Load Docker image
      run: |
        make docker-build
        kind load docker-image controller:latest

    # - name: Deploy CRDs
    #   run: make install

    - name: Deploy controller
      run: |
        make kustomize
        make deploy IMG=controller:latest
        # cd config/manager && ../../bin/kustomize edit set image controller=controller:latest
        # cd ../../ && make deploy IMG=controller:latest

    - name: Wait for controller to be ready
      run: |
        kubectl wait --for=condition=Available deployment/tfout-controller-manager \
          -n tfout --timeout=60s

    - name: Run E2E tests
      run: make test-e2e